# You need to set APP_PATH when running this compose file:
# e.g. APP_PATH=github.com/hashicorp/terraform docker-compose up
version: '3'
services:
  redis:
    image: redis
  # change this key to the name of your app
  my_go_app:
    restart: always
    image: bastipaeltz/go-dev
    working_dir: /go/src/${APP_PATH}
    entrypoint: /go/bin/fresh
    volumes:
      - ${GOPATH}/src/${APP_PATH}:/go/src/${APP_PATH}
    ports:
      # define all app-specific exposed port mappings here
      - "8888:8080"
  # change this key to the name of your app and append "_debug"
  my_go_app_debug:
    restart: always
    image: bastipaeltz/go-dev
    security_opt:
      - seccomp:unconfined
    working_dir: /go/src/${APP_PATH}
    entrypoint: /go/bin/dlv debug --accept-multiclient --listen 0.0.0.0:23456 --headless
    volumes:
      - ${GOPATH}/src/${APP_PATH}:/go/src/${APP_PATH}
    ports:
      - "23456:23456"
      # define all app-specific exposed port mappings here
      - "8889:8080"
